USE [master]
GO

/****** Object:  Database [DonBest]    Script Date: 6/29/2017 7:41:22 AM ******/
CREATE DATABASE [DonBest] ON  PRIMARY 
( NAME = N'DonBest', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\DonBest.mdf' , SIZE = 19456KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DonBest_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\DonBest_log.ldf' , SIZE = 35712KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DonBest] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DonBest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DonBest] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DonBest] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DonBest] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DonBest] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DonBest] SET ARITHABORT OFF 
GO

ALTER DATABASE [DonBest] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DonBest] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DonBest] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DonBest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DonBest] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DonBest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DonBest] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DonBest] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DonBest] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DonBest] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DonBest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DonBest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DonBest] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DonBest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DonBest] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DonBest] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DonBest] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DonBest] SET RECOVERY FULL 
GO

ALTER DATABASE [DonBest] SET  MULTI_USER 
GO

ALTER DATABASE [DonBest] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DonBest] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DonBest] SET  READ_WRITE 
GO

