//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CACtiveMQSubscribe
{
    using System;
    using System.Collections.Generic;
    
    public partial class matchup_score_event_id
    {
        public int id_feed_matchup_score { get; set; }
        public Nullable<int> event_id { get; set; }
        public Nullable<int> away_rot { get; set; }
        public Nullable<int> away_score { get; set; }
        public Nullable<int> home_rot { get; set; }
        public Nullable<int> home_score { get; set; }
        public Nullable<int> sequence { get; set; }
        public string period { get; set; }
        public string description { get; set; }
        public Nullable<bool> final { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<System.DateTime> message_timestamp { get; set; }
        public Nullable<int> league_id { get; set; }
        public Nullable<int> sport_id { get; set; }
    }
}
