//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CACtiveMQSubscribe
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DonBestEntities1 : DbContext
    {
        public DonBestEntities1()
            : base("name=DonBestEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<getAllLines_Result> getAllLines()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAllLines_Result>("getAllLines");
        }
    }
}
