//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CACtiveMQSubscribe
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_all_line
    {
        public Nullable<int> rot { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public Nullable<int> period_id { get; set; }
        public string period { get; set; }
        public Nullable<int> event_id { get; set; }
        public Nullable<short> sportsbook { get; set; }
        public string description { get; set; }
        public Nullable<int> league_id { get; set; }
        public Nullable<int> sport_id { get; set; }
        public Nullable<int> away_team_id { get; set; }
        public Nullable<int> home_team_id { get; set; }
        public Nullable<float> away_spread { get; set; }
        public Nullable<int> away_price { get; set; }
        public Nullable<float> home_spread { get; set; }
        public Nullable<int> home_price { get; set; }
        public int idFeedLine { get; set; }
        public Nullable<int> draw_price { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> home_rot { get; set; }
        public Nullable<float> total_total { get; set; }
        public Nullable<int> over_price { get; set; }
        public Nullable<int> under_price { get; set; }
    }
}
